global:
  controlPlaneSecurityEnabled: false
  defaultPodDisruptionBudget:
    enabled: false

  mtls:
    enabled: false

  proxy:
    resources:
      requests:
        cpu: 10m

gateways:
  istio-ingressgateway:
    autoscaleEnabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
    sds:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 128Mi

certmanager:
  enabled: true
  tag: v0.10.1

kiali:
  enabled: false

tracing:
  enabled: false

pilot:
  autoscaleEnabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi

prometheus:
  enabled: false

mixer:
  telemetry:
    enabled: false