# Note: A future version of Riser may require mTLS
# See also: https://istio.io/latest/docs/concepts/security/#dependency-on-mutual-tls
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: STRICT