# https://github.com/fluxcd/flux/blob/master/chart/flux/values.yaml
image:
  tag: "1.20.1"
env:
  secretName: flux-git
git:
  url: $(GIT_URL)
  path: $(GIT_PATH)
  branch: main
  readonly: true
  pollInterval: 10s
memcached:
  enabled: false
registry:
  disableScanning: true
sync:
  interval: 5m
syncGarbageCollection:
  enabled: true